/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NeighborhoodsRouteImport } from './routes/neighborhoods'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as MarketRouteImport } from './routes/market'
import { Route as MapRouteImport } from './routes/map'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NeighborhoodsIndexRouteImport } from './routes/neighborhoods.index'
import { Route as PropertyIdRouteImport } from './routes/property.$id'
import { Route as NeighborhoodsSlugRouteImport } from './routes/neighborhoods.$slug'

const NeighborhoodsRoute = NeighborhoodsRouteImport.update({
  id: '/neighborhoods',
  path: '/neighborhoods',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NeighborhoodsIndexRoute = NeighborhoodsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NeighborhoodsRoute,
} as any)
const PropertyIdRoute = PropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NeighborhoodsSlugRoute = NeighborhoodsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NeighborhoodsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/market': typeof MarketRoute
  '/methodology': typeof MethodologyRoute
  '/neighborhoods': typeof NeighborhoodsRouteWithChildren
  '/neighborhoods/$slug': typeof NeighborhoodsSlugRoute
  '/property/$id': typeof PropertyIdRoute
  '/neighborhoods/': typeof NeighborhoodsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/market': typeof MarketRoute
  '/methodology': typeof MethodologyRoute
  '/neighborhoods/$slug': typeof NeighborhoodsSlugRoute
  '/property/$id': typeof PropertyIdRoute
  '/neighborhoods': typeof NeighborhoodsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/market': typeof MarketRoute
  '/methodology': typeof MethodologyRoute
  '/neighborhoods': typeof NeighborhoodsRouteWithChildren
  '/neighborhoods/$slug': typeof NeighborhoodsSlugRoute
  '/property/$id': typeof PropertyIdRoute
  '/neighborhoods/': typeof NeighborhoodsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/map'
    | '/market'
    | '/methodology'
    | '/neighborhoods'
    | '/neighborhoods/$slug'
    | '/property/$id'
    | '/neighborhoods/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/map'
    | '/market'
    | '/methodology'
    | '/neighborhoods/$slug'
    | '/property/$id'
    | '/neighborhoods'
  id:
    | '__root__'
    | '/'
    | '/map'
    | '/market'
    | '/methodology'
    | '/neighborhoods'
    | '/neighborhoods/$slug'
    | '/property/$id'
    | '/neighborhoods/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapRoute: typeof MapRoute
  MarketRoute: typeof MarketRoute
  MethodologyRoute: typeof MethodologyRoute
  NeighborhoodsRoute: typeof NeighborhoodsRouteWithChildren
  PropertyIdRoute: typeof PropertyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/neighborhoods': {
      id: '/neighborhoods'
      path: '/neighborhoods'
      fullPath: '/neighborhoods'
      preLoaderRoute: typeof NeighborhoodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neighborhoods/': {
      id: '/neighborhoods/'
      path: '/'
      fullPath: '/neighborhoods/'
      preLoaderRoute: typeof NeighborhoodsIndexRouteImport
      parentRoute: typeof NeighborhoodsRoute
    }
    '/property/$id': {
      id: '/property/$id'
      path: '/property/$id'
      fullPath: '/property/$id'
      preLoaderRoute: typeof PropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neighborhoods/$slug': {
      id: '/neighborhoods/$slug'
      path: '/$slug'
      fullPath: '/neighborhoods/$slug'
      preLoaderRoute: typeof NeighborhoodsSlugRouteImport
      parentRoute: typeof NeighborhoodsRoute
    }
  }
}

interface NeighborhoodsRouteChildren {
  NeighborhoodsSlugRoute: typeof NeighborhoodsSlugRoute
  NeighborhoodsIndexRoute: typeof NeighborhoodsIndexRoute
}

const NeighborhoodsRouteChildren: NeighborhoodsRouteChildren = {
  NeighborhoodsSlugRoute: NeighborhoodsSlugRoute,
  NeighborhoodsIndexRoute: NeighborhoodsIndexRoute,
}

const NeighborhoodsRouteWithChildren = NeighborhoodsRoute._addFileChildren(
  NeighborhoodsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapRoute: MapRoute,
  MarketRoute: MarketRoute,
  MethodologyRoute: MethodologyRoute,
  NeighborhoodsRoute: NeighborhoodsRouteWithChildren,
  PropertyIdRoute: PropertyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
